name: Java CI with Maven  # This is the name of the workflow (appears in GitHub)
on:
  push:
    branches: [ main ]  # Runs when you push to the `main` branch
  pull_request:
    branches: [ main ]  # Runs when you open a pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Uses Ubuntu for the test environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your code into the environment
      - name: Set Up JDK 17
        uses: actions/setup-java@v3  # Installs Java 17
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B verify  # Runs Maven to compile + test your project
